version: '3.8'

services:
  # Generic Reverse Proxy - PRODUCTION READY
  reverse-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config:/app/config
      - ./scripts:/app/scripts
      - ./templates:/app/templates
      - ./static:/var/www/html
      - ./letsencrypt:/etc/letsencrypt
      - ./logs:/var/log/nginx
      - ./web:/var/www/html/advisorassist  # Mount the existing web app
    networks:
      - proxy-network
    restart: always
    environment:
      - CONFIG_FILE=/app/config/hosts.yaml

networks:
  proxy-network:
    driver: bridge